version: '3.8'
services:
  client:
    build: 
      context: ./client
      args:
        VITE_API_URL: http://localhost:4000
    container_name: easyrsvp_client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server
    container_name: easyrsvp_server
    environment:
      - DATABASE_URL=postgres://easyrsvp:easyrsvp@db:5432/easyrsvp_db
      - JWT_SECRET=sample_secret
    ports:
      - "4000:4000"
    depends_on:
      - db
    # command: sh -c "npx prisma migrate deploy && npm start"
  db:
    image: postgres:latest
    restart: always
    container_name: easyrsvp_db
    environment:
      POSTGRES_USER: easyrsvp
      POSTGRES_PASSWORD: easyrsvp
      POSTGRES_DB: easyrsvp_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: